# Generated by Django 5.2.1 on 2025-05-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='ID Telegram User')),
                ('username', models.CharField(max_length=32, verbose_name='Username')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
